/**
 * Helpers for guided Fly.io install / auth / secrets / deploy from the Setup Wizard.
 */

import { existsSync, mkdirSync, writeFileSync, readFileSync, copyFileSync } from "node:fs";
import { join } from "node:path";
import { execFileSync, spawn, type ChildProcess } from "node:child_process";
import { homedir } from "node:os";
import { randomBytes } from "node:crypto";

export interface FlyStatus {
  installed: boolean;
  flyPath: string | null;
  version: string | null;
  loggedIn: boolean;
  whoami: string | null;
  message: string;
}

export interface FlyDeployInput {
  appName: string;
  region?: string;
  googleClientId: string;
  googleClientSecret: string;
  supabaseUrl: string;
  supabaseServiceRoleKey: string;
  mcpApiKey?: string;
  authorizeHashKey?: string;
  tokenEncryptionKey?: string;
  /** Optional Google Ads developer token — never commit; Fly secret only. */
  adsDeveloperToken?: string;
  adsLoginCustomerId?: string;
  adsDefaultCustomerId?: string;
  adsMaxDailyBudgetMicros?: string;
}

export interface FlyDeployResult {
  ok: boolean;
  log: string;
  appUrl?: string;
  authorizeUrl?: string;
  redirectUri?: string;
  cursorRemoteSnippet?: string;
  error?: string;
}

function whichFly(): string | null {
  const candidates = [
    process.env.FLYCTL_INSTALL ? join(process.env.FLYCTL_INSTALL, "bin", "flyctl") : "",
    join(homedir(), ".fly", "bin", "flyctl"),
    join(homedir(), ".fly", "bin", "fly"),
    "/opt/homebrew/bin/flyctl",
    "/usr/local/bin/flyctl",
    "flyctl",
    "fly",
  ].filter(Boolean);

  for (const candidate of candidates) {
    try {
      if (candidate.includes("/") && !existsSync(candidate)) continue;
      execFileSync(candidate, ["version"], { stdio: "ignore" });
      return candidate;
    } catch {
      // try next
    }
  }
  return null;
}

export function getFlyStatus(): FlyStatus {
  const flyPath = whichFly();
  if (!flyPath) {
    return {
      installed: false,
      flyPath: null,
      version: null,
      loggedIn: false,
      whoami: null,
      message: "Fly.io CLI is not installed yet.",
    };
  }

  let version: string | null = null;
  try {
    version = execFileSync(flyPath, ["version"], { encoding: "utf8" }).trim();
  } catch {
    version = null;
  }

  let whoami: string | null = null;
  let loggedIn = false;
  try {
    whoami = execFileSync(flyPath, ["auth", "whoami"], { encoding: "utf8" }).trim();
    loggedIn = Boolean(whoami && !/error|not logged/i.test(whoami));
  } catch {
    loggedIn = false;
  }

  return {
    installed: true,
    flyPath,
    version,
    loggedIn,
    whoami,
    message: loggedIn
      ? `Signed in as ${whoami}`
      : "Fly CLI installed — sign in next.",
  };
}

export function installFlyCli(): { ok: boolean; log: string } {
  try {
    if (process.platform === "win32") {
      const log = execFileSync(
        "powershell",
        [
          "-NoProfile",
          "-Command",
          "iwr https://fly.io/install.ps1 -useb | iex",
        ],
        { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] },
      );
      return { ok: true, log };
    }

    const log = execFileSync(
      "bash",
      ["-lc", "curl -L https://fly.io/install.sh | sh"],
      { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] },
    );
    return { ok: true, log };
  } catch (error) {
    const err = error as { stdout?: string; stderr?: string; message?: string };
    return {
      ok: false,
      log: [err.stdout, err.stderr, err.message].filter(Boolean).join("\n"),
    };
  }
}

/** Starts `fly auth login` (opens browser). Returns the child so callers can wait. */
export function startFlyAuthLogin(): {
  ok: boolean;
  error?: string;
  process?: ChildProcess;
} {
  const flyPath = whichFly();
  if (!flyPath) {
    return { ok: false, error: "Install the Fly CLI first." };
  }
  const child = spawn(flyPath, ["auth", "login"], {
    stdio: ["ignore", "pipe", "pipe"],
    env: process.env,
  });
  return { ok: true, process: child };
}

function sanitizeAppName(raw: string): string {
  return raw
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 30);
}

function ensureDeployDockerfile(appRoot: string): void {
  const dockerfilePath = join(appRoot, "Dockerfile");
  // Prefer a fly-ready Dockerfile that uses prebuilt dist/src JS when present.
  const flyDocker = join(appRoot, "Dockerfile.fly");
  if (existsSync(flyDocker)) {
    copyFileSync(flyDocker, dockerfilePath);
    return;
  }
  if (!existsSync(dockerfilePath)) {
    writeFileSync(
      dockerfilePath,
      `FROM node:22-slim
WORKDIR /app
ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=8080
COPY package.json package-lock.json ./
RUN npm ci --omit=dev
COPY src ./dist
EXPOSE 8080
CMD ["node", "dist/http.js"]
`,
      "utf8",
    );
  }
}

function writeFlyToml(appRoot: string, appName: string, region: string): void {
  const contents = `# Generated by BrandMatchGrowth Google Workspace MCP Setup Wizard
app = ${JSON.stringify(appName)}
primary_region = ${JSON.stringify(region)}

[build]
  dockerfile = "Dockerfile"

[env]
  HOST = "0.0.0.0"
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    grace_period = "60s"
    interval = "30s"
    method = "GET"
    path = "/health"
    timeout = "5s"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
`;
  writeFileSync(join(appRoot, "fly.toml"), contents, "utf8");
}

function runFly(
  flyPath: string,
  args: string[],
  cwd: string,
): { ok: boolean; log: string } {
  try {
    const log = execFileSync(flyPath, args, {
      cwd,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
      env: process.env,
      maxBuffer: 20 * 1024 * 1024,
    });
    return { ok: true, log };
  } catch (error) {
    const err = error as { stdout?: string; stderr?: string; message?: string };
    return {
      ok: false,
      log: [err.stdout, err.stderr, err.message].filter(Boolean).join("\n"),
    };
  }
}

export function deployToFly(appRoot: string, input: FlyDeployInput): FlyDeployResult {
  const logs: string[] = [];
  const flyPath = whichFly();
  if (!flyPath) {
    return { ok: false, log: "", error: "Fly CLI not installed." };
  }

  const status = getFlyStatus();
  if (!status.loggedIn) {
    return { ok: false, log: "", error: "Sign in to Fly.io first." };
  }

  const appName = sanitizeAppName(input.appName);
  if (!appName || appName.length < 3) {
    return {
      ok: false,
      log: "",
      error: "App name must be at least 3 characters (letters, numbers, dashes).",
    };
  }

  if (!input.googleClientId || !input.googleClientSecret) {
    return { ok: false, log: "", error: "Google Client ID and Secret are required." };
  }
  if (!input.supabaseUrl || !input.supabaseServiceRoleKey) {
    return {
      ok: false,
      log: "",
      error: "Supabase URL and service role key are required for multi-account on Fly.",
    };
  }

  const region = (input.region || "yyz").trim();
  const mcpApiKey = input.mcpApiKey?.trim() || randomBytes(24).toString("hex");
  const authorizeHashKey =
    input.authorizeHashKey?.trim() || randomBytes(24).toString("hex");
  const tokenEncryptionKey =
    input.tokenEncryptionKey?.trim() || randomBytes(32).toString("hex");
  const redirectUri = `https://${appName}.fly.dev/oauth2callback`;
  const appUrl = `https://${appName}.fly.dev`;

  ensureDeployDockerfile(appRoot);
  writeFlyToml(appRoot, appName, region);
  logs.push(`Wrote fly.toml for app ${appName} (${region})`);

  // Create app if missing
  const appsList = runFly(flyPath, ["apps", "list", "--json"], appRoot);
  logs.push(appsList.log);
  let exists = false;
  if (appsList.ok) {
    try {
      const parsed = JSON.parse(appsList.log) as Array<{ Name?: string; name?: string }>;
      exists = parsed.some(
        (row) => (row.Name ?? row.name ?? "").toLowerCase() === appName,
      );
    } catch {
      // ignore parse — try create
    }
  }
  if (!exists) {
    const created = runFly(
      flyPath,
      ["apps", "create", appName, "--org", "personal"],
      appRoot,
    );
    logs.push(created.log);
    if (!created.ok && !/already exists/i.test(created.log)) {
      // retry without org
      const created2 = runFly(flyPath, ["apps", "create", appName], appRoot);
      logs.push(created2.log);
      if (!created2.ok && !/already exists/i.test(created2.log)) {
        return {
          ok: false,
          log: logs.join("\n\n"),
          error: "Could not create Fly app. Check the log — you may need to pick another name.",
        };
      }
    }
  }

  const secretsArgs = [
    "secrets",
    "set",
    "-a",
    appName,
    `GOOGLE_OAUTH_CLIENT_ID=${input.googleClientId}`,
    `GOOGLE_OAUTH_CLIENT_SECRET=${input.googleClientSecret}`,
    `GOOGLE_OAUTH_REDIRECT_URI=${redirectUri}`,
    "GOOGLE_ACCOUNTS_STORE=supabase",
    `SUPABASE_URL=${input.supabaseUrl}`,
    `SUPABASE_SERVICE_ROLE_KEY=${input.supabaseServiceRoleKey}`,
    `GOOGLE_TOKEN_ENCRYPTION_KEY=${tokenEncryptionKey}`,
    `MCP_API_KEY=${mcpApiKey}`,
    `AUTHORIZE_HASH_KEY=${authorizeHashKey}`,
    // Spend-safe defaults for Cloud / remote MCP — wizard never enables live ads.
    "GOOGLE_ADS_ALLOW_ENABLE=false",
    `GOOGLE_ADS_MAX_DAILY_BUDGET_MICROS=${input.adsMaxDailyBudgetMicros?.trim() || "25000000"}`,
  ];
  if (input.adsDeveloperToken?.trim()) {
    secretsArgs.push(`GOOGLE_ADS_DEVELOPER_TOKEN=${input.adsDeveloperToken.trim()}`);
  }
  if (input.adsLoginCustomerId?.trim()) {
    secretsArgs.push(
      `GOOGLE_ADS_LOGIN_CUSTOMER_ID=${input.adsLoginCustomerId.replace(/-/g, "").trim()}`,
    );
  }
  if (input.adsDefaultCustomerId?.trim()) {
    secretsArgs.push(
      `GOOGLE_ADS_DEFAULT_CUSTOMER_ID=${input.adsDefaultCustomerId.replace(/-/g, "").trim()}`,
    );
  }
  const secrets = runFly(flyPath, secretsArgs, appRoot);
  logs.push(secrets.log);
  if (!secrets.ok) {
    return {
      ok: false,
      log: logs.join("\n\n"),
      error: "Failed to set Fly secrets.",
    };
  }

  const deploy = runFly(
    flyPath,
    ["deploy", "-a", appName, "--remote-only", "--yes"],
    appRoot,
  );
  logs.push(deploy.log);
  if (!deploy.ok) {
    return {
      ok: false,
      log: logs.join("\n\n"),
      error: "fly deploy failed. See log for details.",
    };
  }

  // Persist generated keys into a local deploy-notes file (not secrets dump to chat)
  const notesPath = join(homedir(), ".config", "google-workspace-mcp", `fly-${appName}.json`);
  mkdirSync(join(homedir(), ".config", "google-workspace-mcp"), { recursive: true });
  writeFileSync(
    notesPath,
    JSON.stringify(
      {
        appName,
        appUrl,
        redirectUri,
        authorizeUrl: `${appUrl}/authorize?hashKey=${authorizeHashKey}`,
        mcpUrl: `${appUrl}/mcp`,
        mcpApiKey,
        authorizeHashKey,
        savedAt: new Date().toISOString(),
      },
      null,
      2,
    ),
    "utf8",
  );

  const cursorRemoteSnippet = JSON.stringify(
    {
      mcpServers: {
        "google-workspace-remote": {
          url: `${appUrl}/mcp`,
          headers: {
            Authorization: `Bearer ${mcpApiKey}`,
          },
        },
      },
    },
    null,
    2,
  );

  return {
    ok: true,
    log: logs.join("\n\n"),
    appUrl,
    authorizeUrl: `${appUrl}/authorize?hashKey=${authorizeHashKey}`,
    redirectUri,
    cursorRemoteSnippet,
  };
}

export function readMigrationSql(repoRoot: string): string {
  const path = join(
    repoRoot,
    "supabase",
    "migrations",
    "20260722000000_google_mcp_oauth_accounts.sql",
  );
  if (existsSync(path)) return readFileSync(path, "utf8");
  // Packaged layout may nest under mcp/
  const alt = join(
    repoRoot,
    "migrations",
    "20260722000000_google_mcp_oauth_accounts.sql",
  );
  if (existsSync(alt)) return readFileSync(alt, "utf8");
  return `-- Create this table in the Supabase SQL Editor, then click Run.

CREATE TABLE IF NOT EXISTS public.google_mcp_oauth_accounts (
  email text PRIMARY KEY,
  label text,
  refresh_token_encrypted text NOT NULL,
  access_token text,
  expiry_date bigint,
  token_type text,
  scope text,
  is_default boolean NOT NULL DEFAULT false,
  authorized_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.google_mcp_oauth_accounts ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.google_mcp_oauth_accounts TO service_role;
`;
}
