#!/usr/bin/env node
/**
 * Beginner-friendly local setup wizard for Google Workspace MCP.
 * Serves a guided UI on http://127.0.0.1:3951 — no coding required.
 */

import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { createServer as createNetServer } from "node:net";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
  copyFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { createOAuthClientForSetup, getAuthorizationUrl } from "../src/auth/googleAuth.js";
import { saveAuthorizedAccount, getAccountStore } from "../src/auth/accountStore.js";
import { createOAuthState, consumeOAuthState } from "../src/auth/oauthStateStore.js";
import { renderAuthorizationCompleteHtml } from "../src/auth/authorizeCompleteHtml.js";
import { loadEnvFile } from "../src/loadEnv.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const PUBLIC = join(__dirname, "public");
const WIZARD_PORT = Number(process.env.SETUP_WIZARD_PORT ?? 3951);
const OAUTH_CALLBACK_PORT = 3847;
const OAUTH_REDIRECT = `http://127.0.0.1:${OAUTH_CALLBACK_PORT}/oauth2callback`;

loadEnvFile();

type JsonBody = Record<string, unknown>;

function sendJson(res: ServerResponse, status: number, body: unknown): void {
  const payload = JSON.stringify(body, null, 2);
  res.writeHead(status, {
    "Content-Type": "application/json; charset=utf-8",
    "Cache-Control": "no-store",
  });
  res.end(payload);
}

function sendText(res: ServerResponse, status: number, body: string, type: string): void {
  res.writeHead(status, { "Content-Type": type, "Cache-Control": "no-store" });
  res.end(body);
}

function readBody(req: IncomingMessage): Promise<string> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    req.on("data", (chunk: Buffer) => chunks.push(chunk));
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", reject);
  });
}

async function readJson(req: IncomingMessage): Promise<JsonBody> {
  const raw = await readBody(req);
  if (!raw.trim()) return {};
  return JSON.parse(raw) as JsonBody;
}

function openBrowser(url: string): void {
  try {
    if (process.platform === "darwin") {
      execSync(`open ${JSON.stringify(url)}`, { stdio: "ignore" });
      return;
    }
    if (process.platform === "win32") {
      execSync(`start "" ${JSON.stringify(url)}`, {
        stdio: "ignore",
        shell: "cmd.exe",
      });
      return;
    }
    execSync(`xdg-open ${JSON.stringify(url)}`, { stdio: "ignore" });
  } catch {
    console.log(`Open this URL in your browser:\n${url}\n`);
  }
}

function parseEnvFile(path: string): Record<string, string> {
  if (!existsSync(path)) return {};
  const out: Record<string, string> = {};
  for (const line of readFileSync(path, "utf8").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const separator = trimmed.indexOf("=");
    if (separator === -1) continue;
    const key = trimmed.slice(0, separator).trim();
    let value = trimmed.slice(separator + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

function writeEnvFile(values: Record<string, string>): void {
  const envPath = join(ROOT, ".env");
  const existing = parseEnvFile(envPath);
  const merged = { ...existing, ...values };

  if (!merged.GOOGLE_OAUTH_REDIRECT_URI) {
    merged.GOOGLE_OAUTH_REDIRECT_URI = OAUTH_REDIRECT;
  }
  if (!merged.AUTHORIZE_HASH_KEY) {
    merged.AUTHORIZE_HASH_KEY = randomBytes(24).toString("hex");
  }
  if (!merged.GOOGLE_TASKS_DEFAULT_LIST) {
    merged.GOOGLE_TASKS_DEFAULT_LIST = "Action items";
  }

  const lines = [
    "# Generated by Google Workspace MCP Setup Wizard",
    "# Do not commit this file — it contains secrets.",
    "",
    `GOOGLE_OAUTH_CLIENT_ID=${merged.GOOGLE_OAUTH_CLIENT_ID ?? ""}`,
    `GOOGLE_OAUTH_CLIENT_SECRET=${merged.GOOGLE_OAUTH_CLIENT_SECRET ?? ""}`,
    `GOOGLE_OAUTH_REDIRECT_URI=${merged.GOOGLE_OAUTH_REDIRECT_URI}`,
    `AUTHORIZE_HASH_KEY=${merged.AUTHORIZE_HASH_KEY}`,
    `GOOGLE_TASKS_DEFAULT_LIST=${merged.GOOGLE_TASKS_DEFAULT_LIST}`,
    "",
  ];

  if (merged.GOOGLE_DEFAULT_ACCOUNT_EMAIL) {
    lines.push(`GOOGLE_DEFAULT_ACCOUNT_EMAIL=${merged.GOOGLE_DEFAULT_ACCOUNT_EMAIL}`);
    lines.push("");
  }

  writeFileSync(envPath, lines.join("\n"), "utf8");

  for (const [key, value] of Object.entries(merged)) {
    process.env[key] = value;
  }
}

function nodeReady(): { ok: boolean; version: string; message: string } {
  const version = process.version;
  const major = Number(version.slice(1).split(".")[0]);
  if (major < 20) {
    return {
      ok: false,
      version,
      message: `Node.js 20+ is required. You have ${version}. Install from https://nodejs.org`,
    };
  }
  return { ok: true, version, message: `Node.js ${version}` };
}

function depsInstalled(): boolean {
  return existsSync(join(ROOT, "node_modules", "@modelcontextprotocol", "sdk"));
}

function distBuilt(): boolean {
  return existsSync(join(ROOT, "dist", "index.js"));
}

async function listAccountsSafe(): Promise<
  Array<{ email: string; label?: string; isDefault: boolean }>
> {
  try {
    const store = getAccountStore();
    await store.migrateLegacyIfNeeded();
    return await store.listAccounts();
  } catch {
    return [];
  }
}

function cursorMcpSnippet(absoluteDist: string, env: Record<string, string>): string {
  return JSON.stringify(
    {
      mcpServers: {
        "google-workspace": {
          command: "node",
          args: [absoluteDist],
          env: {
            GOOGLE_OAUTH_CLIENT_ID: env.GOOGLE_OAUTH_CLIENT_ID ?? "",
            GOOGLE_OAUTH_CLIENT_SECRET: env.GOOGLE_OAUTH_CLIENT_SECRET ?? "",
            GOOGLE_OAUTH_REDIRECT_URI:
              env.GOOGLE_OAUTH_REDIRECT_URI ?? OAUTH_REDIRECT,
          },
        },
      },
    },
    null,
    2,
  );
}

function cursorConfigPaths(): string[] {
  const home = process.env.HOME ?? process.env.USERPROFILE ?? "";
  if (process.platform === "darwin") {
    return [
      join(home, ".cursor", "mcp.json"),
      join(
        home,
        "Library",
        "Application Support",
        "Cursor",
        "User",
        "globalStorage",
        "cursor.mcp",
        "mcp.json",
      ),
    ];
  }
  if (process.platform === "win32") {
    const appData = process.env.APPDATA ?? join(home, "AppData", "Roaming");
    return [join(home, ".cursor", "mcp.json"), join(appData, "Cursor", "User", "mcp.json")];
  }
  return [join(home, ".cursor", "mcp.json")];
}

async function runInstall(): Promise<{ ok: boolean; log: string }> {
  try {
    const log = execSync("npm install && npm run build", {
      cwd: ROOT,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
      env: { ...process.env, npm_config_fund: "false" },
    });
    return { ok: true, log };
  } catch (error) {
    const err = error as { stdout?: string; stderr?: string; message?: string };
    return {
      ok: false,
      log: [err.stdout, err.stderr, err.message].filter(Boolean).join("\n"),
    };
  }
}

let oauthServer: ReturnType<typeof createServer> | null = null;
let oauthBusy = false;

async function portFree(port: number): Promise<boolean> {
  return new Promise((resolve) => {
    const tester = createNetServer()
      .once("error", () => resolve(false))
      .once("listening", () => {
        tester.close(() => resolve(true));
      })
      .listen(port, "127.0.0.1");
  });
}

async function startAuthorize(label?: string): Promise<{ ok: boolean; authUrl?: string; error?: string }> {
  if (oauthBusy) {
    return { ok: false, error: "An authorization is already in progress. Finish or cancel it first." };
  }

  const env = parseEnvFile(join(ROOT, ".env"));
  if (!env.GOOGLE_OAUTH_CLIENT_ID?.trim() || !env.GOOGLE_OAUTH_CLIENT_SECRET?.trim()) {
    return {
      ok: false,
      error: "Save your Google Client ID and Client Secret first (step 2).",
    };
  }

  for (const [key, value] of Object.entries(env)) {
    process.env[key] = value;
  }

  if (!(await portFree(OAUTH_CALLBACK_PORT))) {
    return {
      ok: false,
      error: `Port ${OAUTH_CALLBACK_PORT} is busy. Close any other authorize window and try again.`,
    };
  }

  const oauth = createOAuthClientForSetup();
  const statePayload = JSON.stringify({
    nonce: createOAuthState(),
    label: label?.trim() || undefined,
  });
  const state = Buffer.from(statePayload, "utf8").toString("base64url");
  const authUrl = getAuthorizationUrl(oauth, state);

  oauthBusy = true;

  oauthServer = createServer(async (req, res) => {
    if (!req.url?.startsWith("/oauth2callback")) {
      res.writeHead(404, { "Content-Type": "text/plain" });
      res.end("Not found");
      return;
    }

    const url = new URL(req.url, OAUTH_REDIRECT);
    const code = url.searchParams.get("code");
    const error = url.searchParams.get("error");
    const stateRaw = url.searchParams.get("state");

    const finish = (): void => {
      oauthBusy = false;
      oauthServer?.close();
      oauthServer = null;
    };

    if (error) {
      sendText(
        res,
        400,
        `<h1>Authorization failed</h1><p>${error}</p><p>You can close this tab and try again in the setup wizard.</p>`,
        "text/html; charset=utf-8",
      );
      finish();
      return;
    }

    if (!code) {
      sendText(res, 400, "<h1>Missing authorization code</h1>", "text/html; charset=utf-8");
      return;
    }

    let parsedLabel = label?.trim() || undefined;
    if (stateRaw) {
      try {
        const parsed = JSON.parse(
          Buffer.from(stateRaw, "base64url").toString("utf8"),
        ) as { nonce?: string; label?: string };
        if (parsed.nonce && !consumeOAuthState(parsed.nonce)) {
          sendText(res, 400, "<h1>Invalid OAuth state</h1>", "text/html; charset=utf-8");
          finish();
          return;
        }
        parsedLabel = parsed.label ?? parsedLabel;
      } catch {
        // ignore
      }
    }

    try {
      const { tokens } = await oauth.getToken(code);
      const account = await saveAuthorizedAccount(
        {
          refresh_token: tokens.refresh_token ?? undefined,
          access_token: tokens.access_token ?? undefined,
          expiry_date: tokens.expiry_date ?? undefined,
          token_type: tokens.token_type ?? undefined,
          scope: tokens.scope ?? undefined,
        },
        { label: parsedLabel },
      );
      sendText(res, 200, renderAuthorizationCompleteHtml(account.email), "text/html; charset=utf-8");
      console.log(`Wizard saved account: ${account.email}`);
    } catch (authError) {
      const message = authError instanceof Error ? authError.message : String(authError);
      sendText(
        res,
        500,
        `<h1>Token exchange failed</h1><pre>${message}</pre>`,
        "text/html; charset=utf-8",
      );
    } finally {
      finish();
    }
  });

  await new Promise<void>((resolve, reject) => {
    oauthServer!.listen(OAUTH_CALLBACK_PORT, "127.0.0.1", () => resolve());
    oauthServer!.on("error", reject);
  });

  openBrowser(authUrl);
  return { ok: true, authUrl };
}

function contentTypeFor(filePath: string): string {
  if (filePath.endsWith(".html")) return "text/html; charset=utf-8";
  if (filePath.endsWith(".css")) return "text/css; charset=utf-8";
  if (filePath.endsWith(".js")) return "text/javascript; charset=utf-8";
  if (filePath.endsWith(".png")) return "image/png";
  if (filePath.endsWith(".svg")) return "image/svg+xml";
  return "application/octet-stream";
}

async function handleApi(req: IncomingMessage, res: ServerResponse, url: URL): Promise<void> {
  const path = url.pathname;

  if (req.method === "GET" && path === "/api/status") {
    const env = parseEnvFile(join(ROOT, ".env"));
    const node = nodeReady();
    const accounts = await listAccountsSafe();
    sendJson(res, 200, {
      node,
      depsInstalled: depsInstalled(),
      distBuilt: distBuilt(),
      hasEnv: Boolean(env.GOOGLE_OAUTH_CLIENT_ID && env.GOOGLE_OAUTH_CLIENT_SECRET),
      clientIdPreview: env.GOOGLE_OAUTH_CLIENT_ID
        ? `${env.GOOGLE_OAUTH_CLIENT_ID.slice(0, 18)}…`
        : "",
      redirectUri: env.GOOGLE_OAUTH_REDIRECT_URI ?? OAUTH_REDIRECT,
      accounts,
      oauthBusy,
      platform: process.platform,
      repoRoot: ROOT,
      distPath: join(ROOT, "dist", "index.js"),
      cursorConfigPaths: cursorConfigPaths(),
      version: readPackageVersion(),
    });
    return;
  }

  if (req.method === "POST" && path === "/api/install") {
    const result = await runInstall();
    sendJson(res, result.ok ? 200 : 500, result);
    return;
  }

  if (req.method === "POST" && path === "/api/save-env") {
    const body = await readJson(req);
    const clientId = String(body.clientId ?? "").trim();
    const clientSecret = String(body.clientSecret ?? "").trim();
    if (!clientId || !clientSecret) {
      sendJson(res, 400, { ok: false, error: "Client ID and Client Secret are required." });
      return;
    }
    if (!clientId.includes(".apps.googleusercontent.com")) {
      sendJson(res, 400, {
        ok: false,
        error: "Client ID should look like ….apps.googleusercontent.com",
      });
      return;
    }
    writeEnvFile({
      GOOGLE_OAUTH_CLIENT_ID: clientId,
      GOOGLE_OAUTH_CLIENT_SECRET: clientSecret,
      GOOGLE_OAUTH_REDIRECT_URI: OAUTH_REDIRECT,
    });
    sendJson(res, 200, { ok: true, redirectUri: OAUTH_REDIRECT });
    return;
  }

  if (req.method === "POST" && path === "/api/authorize") {
    const body = await readJson(req);
    const label = typeof body.label === "string" ? body.label : undefined;
    const result = await startAuthorize(label);
    sendJson(res, result.ok ? 200 : 400, result);
    return;
  }

  if (req.method === "POST" && path === "/api/authorize/cancel") {
    oauthBusy = false;
    oauthServer?.close();
    oauthServer = null;
    sendJson(res, 200, { ok: true });
    return;
  }

  if (req.method === "GET" && path === "/api/accounts") {
    sendJson(res, 200, { accounts: await listAccountsSafe(), oauthBusy });
    return;
  }

  if (req.method === "GET" && path === "/api/cursor-config") {
    const env = parseEnvFile(join(ROOT, ".env"));
    const distPath = join(ROOT, "dist", "index.js");
    sendJson(res, 200, {
      snippet: cursorMcpSnippet(distPath, env),
      paths: cursorConfigPaths(),
      distPath,
    });
    return;
  }

  if (req.method === "POST" && path === "/api/write-cursor-config") {
    if (!distBuilt()) {
      sendJson(res, 400, { ok: false, error: "Build the project first (Install step)." });
      return;
    }
    const env = parseEnvFile(join(ROOT, ".env"));
    const distPath = join(ROOT, "dist", "index.js");
    const target = cursorConfigPaths()[0];
    mkdirSync(dirname(target), { recursive: true });

    let existing: { mcpServers?: Record<string, unknown> } = {};
    if (existsSync(target)) {
      try {
        existing = JSON.parse(readFileSync(target, "utf8")) as typeof existing;
      } catch {
        const backup = `${target}.bak-${Date.now()}`;
        copyFileSync(target, backup);
        existing = {};
      }
    }

    const next = {
      ...existing,
      mcpServers: {
        ...(existing.mcpServers ?? {}),
        "google-workspace": {
          command: "node",
          args: [distPath],
          env: {
            GOOGLE_OAUTH_CLIENT_ID: env.GOOGLE_OAUTH_CLIENT_ID ?? "",
            GOOGLE_OAUTH_CLIENT_SECRET: env.GOOGLE_OAUTH_CLIENT_SECRET ?? "",
            GOOGLE_OAUTH_REDIRECT_URI: env.GOOGLE_OAUTH_REDIRECT_URI ?? OAUTH_REDIRECT,
          },
        },
      },
    };

    writeFileSync(target, `${JSON.stringify(next, null, 2)}\n`, "utf8");
    sendJson(res, 200, { ok: true, path: target });
    return;
  }

  sendJson(res, 404, { error: "Not found" });
}

function readPackageVersion(): string {
  try {
    const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8")) as {
      version?: string;
    };
    return pkg.version ?? "0.0.0";
  } catch {
    return "0.0.0";
  }
}

function serveStatic(res: ServerResponse, urlPath: string): void {
  const relative = urlPath === "/" ? "/index.html" : urlPath;
  const safe = join(PUBLIC, relative.replace(/^\/+/, ""));
  if (!safe.startsWith(PUBLIC) || !existsSync(safe)) {
    sendText(res, 404, "Not found", "text/plain");
    return;
  }
  sendText(res, 200, readFileSync(safe, "utf8"), contentTypeFor(safe));
}

const server = createServer(async (req, res) => {
  try {
    const url = new URL(req.url ?? "/", `http://127.0.0.1:${WIZARD_PORT}`);
    if (url.pathname.startsWith("/api/")) {
      await handleApi(req, res, url);
      return;
    }
    serveStatic(res, url.pathname);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    sendJson(res, 500, { error: message });
  }
});

server.listen(WIZARD_PORT, "127.0.0.1", () => {
  const url = `http://127.0.0.1:${WIZARD_PORT}`;
  console.log("\nGoogle Workspace MCP — Setup Wizard\n");
  console.log(`Open: ${url}\n`);
  console.log("Keep this window open while you use the wizard.");
  console.log("Press Ctrl+C when you are finished.\n");
  openBrowser(url);
});

process.on("SIGINT", () => {
  oauthServer?.close();
  server.close();
  process.exit(0);
});
