#!/usr/bin/env node
/**
 * Beginner-friendly local setup wizard for Google Workspace MCP.
 * Serves a guided UI on http://127.0.0.1:3951 — no coding required.
 *
 * Packaged installer (Electron) imports {@link startWizardServer} with openBrowser: false.
 */

import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { createServer as createNetServer } from "node:net";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
  copyFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { execSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { createOAuthClientForSetup, getAuthorizationUrl } from "../src/auth/googleAuth.js";
import { saveAuthorizedAccount, getAccountStore } from "../src/auth/accountStore.js";
import { createOAuthState, consumeOAuthState } from "../src/auth/oauthStateStore.js";
import { renderAuthorizationCompleteHtml } from "../src/auth/authorizeCompleteHtml.js";
import { loadEnvFile } from "../src/loadEnv.js";
import {
  isPackagedInstall,
  resolveAppRoot,
  resolveBundledNodePath,
  resolveUserConfigDir,
  resolveUserEnvPath,
} from "../src/paths.js";
import {
  deployToFly,
  getFlyStatus,
  installFlyCli,
  readMigrationSql,
  startFlyAuthLogin,
} from "./flyAssist.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PUBLIC = join(__dirname, "public");
const DEFAULT_WIZARD_PORT = Number(process.env.SETUP_WIZARD_PORT ?? 3951);
const OAUTH_CALLBACK_PORT = 3847;
const OAUTH_REDIRECT = `http://127.0.0.1:${OAUTH_CALLBACK_PORT}/oauth2callback`;

loadEnvFile();

type JsonBody = Record<string, unknown>;

export interface WizardServerOptions {
  port?: number;
  openBrowser?: boolean;
  /** Override app root (dist + node_modules). */
  appRoot?: string;
}

export interface WizardServerHandle {
  url: string;
  port: number;
  close: () => Promise<void>;
}

function appRoot(options?: WizardServerOptions): string {
  if (options?.appRoot) return options.appRoot;
  // paths.ts lives in src/ (or dist/); its parent is the app/package root.
  return resolveAppRoot();
}

function mcpDistIndex(root: string): string {
  return join(root, "dist", "index.js");
}

function sendJson(res: ServerResponse, status: number, body: unknown): void {
  const payload = JSON.stringify(body, null, 2);
  res.writeHead(status, {
    "Content-Type": "application/json; charset=utf-8",
    "Cache-Control": "no-store",
  });
  res.end(payload);
}

function sendText(res: ServerResponse, status: number, body: string, type: string): void {
  res.writeHead(status, { "Content-Type": type, "Cache-Control": "no-store" });
  res.end(body);
}

function readBody(req: IncomingMessage): Promise<string> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    req.on("data", (chunk: Buffer) => chunks.push(chunk));
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", reject);
  });
}

async function readJson(req: IncomingMessage): Promise<JsonBody> {
  const raw = await readBody(req);
  if (!raw.trim()) return {};
  return JSON.parse(raw) as JsonBody;
}

function openBrowser(url: string): void {
  try {
    if (process.platform === "darwin") {
      execSync(`open ${JSON.stringify(url)}`, { stdio: "ignore" });
      return;
    }
    if (process.platform === "win32") {
      execSync(`start "" ${JSON.stringify(url)}`, {
        stdio: "ignore",
        shell: "cmd.exe",
      });
      return;
    }
    execSync(`xdg-open ${JSON.stringify(url)}`, { stdio: "ignore" });
  } catch {
    console.log(`Open this URL in your browser:\n${url}\n`);
  }
}

function parseEnvFile(path: string): Record<string, string> {
  if (!existsSync(path)) return {};
  const out: Record<string, string> = {};
  for (const line of readFileSync(path, "utf8").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const separator = trimmed.indexOf("=");
    if (separator === -1) continue;
    const key = trimmed.slice(0, separator).trim();
    let value = trimmed.slice(separator + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

function writeEnvFile(values: Record<string, string>): void {
  const envPath = resolveUserEnvPath();
  mkdirSync(dirname(envPath), { recursive: true });
  const existing = parseEnvFile(envPath);
  const merged = { ...existing, ...values };

  if (!merged.GOOGLE_OAUTH_REDIRECT_URI) {
    merged.GOOGLE_OAUTH_REDIRECT_URI = OAUTH_REDIRECT;
  }
  if (!merged.AUTHORIZE_HASH_KEY) {
    merged.AUTHORIZE_HASH_KEY = randomBytes(24).toString("hex");
  }
  if (!merged.GOOGLE_TASKS_DEFAULT_LIST) {
    merged.GOOGLE_TASKS_DEFAULT_LIST = "Action items";
  }

  const lines = [
    "# Generated by BrandMatchGrowth Google Workspace MCP Setup Wizard",
    "# Do not commit this file — it contains secrets.",
    "",
    `GOOGLE_OAUTH_CLIENT_ID=${merged.GOOGLE_OAUTH_CLIENT_ID ?? ""}`,
    `GOOGLE_OAUTH_CLIENT_SECRET=${merged.GOOGLE_OAUTH_CLIENT_SECRET ?? ""}`,
    `GOOGLE_OAUTH_REDIRECT_URI=${merged.GOOGLE_OAUTH_REDIRECT_URI}`,
    `AUTHORIZE_HASH_KEY=${merged.AUTHORIZE_HASH_KEY}`,
    `GOOGLE_TASKS_DEFAULT_LIST=${merged.GOOGLE_TASKS_DEFAULT_LIST}`,
    "",
  ];

  if (merged.GOOGLE_DEFAULT_ACCOUNT_EMAIL) {
    lines.push(`GOOGLE_DEFAULT_ACCOUNT_EMAIL=${merged.GOOGLE_DEFAULT_ACCOUNT_EMAIL}`);
  }
  if (merged.GOOGLE_ACCOUNTS_STORE) {
    lines.push(`GOOGLE_ACCOUNTS_STORE=${merged.GOOGLE_ACCOUNTS_STORE}`);
  }
  if (merged.SUPABASE_URL) {
    lines.push(`SUPABASE_URL=${merged.SUPABASE_URL}`);
  }
  if (merged.SUPABASE_SERVICE_ROLE_KEY) {
    lines.push(`SUPABASE_SERVICE_ROLE_KEY=${merged.SUPABASE_SERVICE_ROLE_KEY}`);
  }
  if (merged.GOOGLE_TOKEN_ENCRYPTION_KEY) {
    lines.push(`GOOGLE_TOKEN_ENCRYPTION_KEY=${merged.GOOGLE_TOKEN_ENCRYPTION_KEY}`);
  }
  if (merged.MCP_API_KEY) {
    lines.push(`MCP_API_KEY=${merged.MCP_API_KEY}`);
  }
  lines.push("");

  writeFileSync(envPath, lines.join("\n"), "utf8");

  for (const [key, value] of Object.entries(merged)) {
    process.env[key] = value;
  }
  process.env.GOOGLE_MCP_ENV_FILE = envPath;
}

function nodeReady(): { ok: boolean; version: string; message: string } {
  if (isPackagedInstall()) {
    const bundled = resolveBundledNodePath();
    return {
      ok: true,
      version: process.version,
      message: bundled
        ? `Installer includes Node.js (bundled) — no separate install needed`
        : `Running inside the installer app — no separate Node.js install needed`,
    };
  }
  const version = process.version;
  const major = Number(version.slice(1).split(".")[0]);
  if (major < 20) {
    return {
      ok: false,
      version,
      message: `Node.js 20+ is required. You have ${version}. Prefer the macOS/Windows installer from GitHub Releases, or install Node from https://nodejs.org`,
    };
  }
  return { ok: true, version, message: `Node.js ${version}` };
}

function depsInstalled(root: string): boolean {
  if (isPackagedInstall()) return true;
  return existsSync(join(root, "node_modules", "@modelcontextprotocol", "sdk"));
}

function distBuilt(root: string): boolean {
  return existsSync(mcpDistIndex(root));
}

async function listAccountsSafe(): Promise<
  Array<{ email: string; label?: string; isDefault: boolean }>
> {
  try {
    const store = getAccountStore();
    await store.migrateLegacyIfNeeded();
    return await store.listAccounts();
  } catch {
    return [];
  }
}

function resolveNodeCommand(root: string): string {
  return resolveBundledNodePath() ?? "node";
}

function cursorMcpSnippet(root: string, envFile: string): string {
  return JSON.stringify(
    {
      mcpServers: {
        "google-workspace": {
          command: resolveNodeCommand(root),
          args: [mcpDistIndex(root)],
          env: {
            GOOGLE_MCP_ENV_FILE: envFile,
            GOOGLE_MCP_APP_ROOT: root,
          },
        },
      },
    },
    null,
    2,
  );
}

function cursorConfigPaths(): string[] {
  const home = process.env.HOME ?? process.env.USERPROFILE ?? "";
  if (process.platform === "darwin") {
    return [
      join(home, ".cursor", "mcp.json"),
      join(
        home,
        "Library",
        "Application Support",
        "Cursor",
        "User",
        "globalStorage",
        "cursor.mcp",
        "mcp.json",
      ),
    ];
  }
  if (process.platform === "win32") {
    const appData = process.env.APPDATA ?? join(home, "AppData", "Roaming");
    return [join(home, ".cursor", "mcp.json"), join(appData, "Cursor", "User", "mcp.json")];
  }
  return [join(home, ".cursor", "mcp.json")];
}

async function runInstall(root: string): Promise<{ ok: boolean; log: string }> {
  if (isPackagedInstall()) {
    return {
      ok: true,
      log: "Installer build already includes dependencies. Nothing to download.",
    };
  }
  try {
    const log = execSync("npm install && npm run build", {
      cwd: root,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
      env: { ...process.env, npm_config_fund: "false" },
    });
    return { ok: true, log };
  } catch (error) {
    const err = error as { stdout?: string; stderr?: string; message?: string };
    return {
      ok: false,
      log: [err.stdout, err.stderr, err.message].filter(Boolean).join("\n"),
    };
  }
}

let oauthServer: ReturnType<typeof createServer> | null = null;
let oauthBusy = false;

async function portFree(port: number): Promise<boolean> {
  return new Promise((resolve) => {
    const tester = createNetServer()
      .once("error", () => resolve(false))
      .once("listening", () => {
        tester.close(() => resolve(true));
      })
      .listen(port, "127.0.0.1");
  });
}

async function startAuthorize(label?: string): Promise<{ ok: boolean; authUrl?: string; error?: string }> {
  if (oauthBusy) {
    return { ok: false, error: "An authorization is already in progress. Finish or cancel it first." };
  }

  loadEnvFile();
  const env = parseEnvFile(resolveUserEnvPath());
  if (!env.GOOGLE_OAUTH_CLIENT_ID?.trim() || !env.GOOGLE_OAUTH_CLIENT_SECRET?.trim()) {
    return {
      ok: false,
      error: "Save your Google Client ID and Client Secret first (Google keys step).",
    };
  }

  for (const [key, value] of Object.entries(env)) {
    process.env[key] = value;
  }

  if (!(await portFree(OAUTH_CALLBACK_PORT))) {
    return {
      ok: false,
      error: `Port ${OAUTH_CALLBACK_PORT} is busy. Close any other authorize window and try again.`,
    };
  }

  const oauth = createOAuthClientForSetup();
  const statePayload = JSON.stringify({
    nonce: createOAuthState(),
    label: label?.trim() || undefined,
  });
  const state = Buffer.from(statePayload, "utf8").toString("base64url");
  const authUrl = getAuthorizationUrl(oauth, state);

  oauthBusy = true;

  oauthServer = createServer(async (req, res) => {
    if (!req.url?.startsWith("/oauth2callback")) {
      res.writeHead(404, { "Content-Type": "text/plain" });
      res.end("Not found");
      return;
    }

    const url = new URL(req.url, OAUTH_REDIRECT);
    const code = url.searchParams.get("code");
    const error = url.searchParams.get("error");
    const stateRaw = url.searchParams.get("state");

    const finish = (): void => {
      oauthBusy = false;
      oauthServer?.close();
      oauthServer = null;
    };

    if (error) {
      sendText(
        res,
        400,
        `<h1>Authorization failed</h1><p>${error}</p><p>You can close this tab and try again in the setup wizard.</p>`,
        "text/html; charset=utf-8",
      );
      finish();
      return;
    }

    if (!code) {
      sendText(res, 400, "<h1>Missing authorization code</h1>", "text/html; charset=utf-8");
      return;
    }

    let parsedLabel = label?.trim() || undefined;
    if (stateRaw) {
      try {
        const parsed = JSON.parse(
          Buffer.from(stateRaw, "base64url").toString("utf8"),
        ) as { nonce?: string; label?: string };
        if (parsed.nonce && !consumeOAuthState(parsed.nonce)) {
          sendText(res, 400, "<h1>Invalid OAuth state</h1>", "text/html; charset=utf-8");
          finish();
          return;
        }
        parsedLabel = parsed.label ?? parsedLabel;
      } catch {
        // ignore
      }
    }

    try {
      const { tokens } = await oauth.getToken(code);
      const account = await saveAuthorizedAccount(
        {
          refresh_token: tokens.refresh_token ?? undefined,
          access_token: tokens.access_token ?? undefined,
          expiry_date: tokens.expiry_date ?? undefined,
          token_type: tokens.token_type ?? undefined,
          scope: tokens.scope ?? undefined,
        },
        { label: parsedLabel },
      );
      sendText(res, 200, renderAuthorizationCompleteHtml(account.email), "text/html; charset=utf-8");
      console.log(`Wizard saved account: ${account.email}`);
    } catch (authError) {
      const message = authError instanceof Error ? authError.message : String(authError);
      sendText(
        res,
        500,
        `<h1>Token exchange failed</h1><pre>${message}</pre>`,
        "text/html; charset=utf-8",
      );
    } finally {
      finish();
    }
  });

  await new Promise<void>((resolve, reject) => {
    oauthServer!.listen(OAUTH_CALLBACK_PORT, "127.0.0.1", () => resolve());
    oauthServer!.on("error", reject);
  });

  openBrowser(authUrl);
  return { ok: true, authUrl };
}

function contentTypeFor(filePath: string): string {
  if (filePath.endsWith(".html")) return "text/html; charset=utf-8";
  if (filePath.endsWith(".css")) return "text/css; charset=utf-8";
  if (filePath.endsWith(".js")) return "text/javascript; charset=utf-8";
  if (filePath.endsWith(".png")) return "image/png";
  if (filePath.endsWith(".svg")) return "image/svg+xml";
  return "application/octet-stream";
}

function readPackageVersion(root: string): string {
  try {
    const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8")) as {
      version?: string;
    };
    return pkg.version ?? "0.0.0";
  } catch {
    return "0.0.0";
  }
}

function serveStatic(res: ServerResponse, urlPath: string): void {
  const relative = urlPath === "/" ? "/index.html" : urlPath;
  const safe = join(PUBLIC, relative.replace(/^\/+/, ""));
  if (!safe.startsWith(PUBLIC) || !existsSync(safe)) {
    sendText(res, 404, "Not found", "text/plain");
    return;
  }
  const body = readFileSync(safe);
  res.writeHead(200, {
    "Content-Type": contentTypeFor(safe),
    "Cache-Control": "no-store",
  });
  res.end(body);
}

export async function startWizardServer(
  options: WizardServerOptions = {},
): Promise<WizardServerHandle> {
  const root = appRoot(options);
  process.env.GOOGLE_MCP_APP_ROOT = root;
  const port = options.port ?? DEFAULT_WIZARD_PORT;
  const shouldOpenBrowser = options.openBrowser ?? true;

  if (!(await portFree(port))) {
    throw new Error(
      `Setup wizard port ${port} is already in use. Close the other Setup window and try again.`,
    );
  }

  const server = createServer(async (req, res) => {
    try {
      const url = new URL(req.url ?? "/", `http://127.0.0.1:${port}`);
      if (url.pathname.startsWith("/api/")) {
        await handleApi(req, res, url, root);
        return;
      }
      serveStatic(res, url.pathname);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      sendJson(res, 500, { error: message });
    }
  });

  await new Promise<void>((resolve, reject) => {
    server.listen(port, "127.0.0.1", () => resolve());
    server.on("error", reject);
  });

  const url = `http://127.0.0.1:${port}`;
  console.log("\nGoogle Workspace MCP — Setup Wizard\n");
  console.log(`Open: ${url}\n`);
  if (shouldOpenBrowser) {
    openBrowser(url);
  }

  return {
    url,
    port,
    close: async () => {
      oauthServer?.close();
      oauthBusy = false;
      await new Promise<void>((resolve) => {
        server.close(() => resolve());
      });
    },
  };
}

async function handleApi(
  req: IncomingMessage,
  res: ServerResponse,
  url: URL,
  root: string,
): Promise<void> {
  const path = url.pathname;
  const envPath = resolveUserEnvPath();
  const packaged = isPackagedInstall();

  if (req.method === "GET" && path === "/api/status") {
    const env = parseEnvFile(envPath);
    const node = nodeReady();
    const accounts = await listAccountsSafe();
    const depsOk = depsInstalled(root);
    const builtOk = distBuilt(root);
    sendJson(res, 200, {
      node,
      depsInstalled: depsOk,
      distBuilt: builtOk,
      packaged,
      hasEnv: Boolean(env.GOOGLE_OAUTH_CLIENT_ID && env.GOOGLE_OAUTH_CLIENT_SECRET),
      hasSupabase: Boolean(env.SUPABASE_URL && env.SUPABASE_SERVICE_ROLE_KEY),
      clientIdPreview: env.GOOGLE_OAUTH_CLIENT_ID
        ? `${env.GOOGLE_OAUTH_CLIENT_ID.slice(0, 18)}…`
        : "",
      supabaseUrlPreview: env.SUPABASE_URL
        ? env.SUPABASE_URL.replace(/^https?:\/\//, "").slice(0, 40)
        : "",
      redirectUri: env.GOOGLE_OAUTH_REDIRECT_URI ?? OAUTH_REDIRECT,
      accounts,
      oauthBusy,
      platform: process.platform,
      repoRoot: root,
      userConfigDir: resolveUserConfigDir(),
      envPath,
      distPath: mcpDistIndex(root),
      bundledNode: resolveBundledNodePath(),
      cursorConfigPaths: cursorConfigPaths(),
      version: readPackageVersion(root),
      fly: getFlyStatus(),
    });
    return;
  }

  if (req.method === "POST" && path === "/api/install") {
    const result = await runInstall(root);
    sendJson(res, result.ok ? 200 : 500, result);
    return;
  }

  if (req.method === "POST" && path === "/api/save-env") {
    const body = await readJson(req);
    const clientId = String(body.clientId ?? "").trim();
    const clientSecret = String(body.clientSecret ?? "").trim();
    if (!clientId || !clientSecret) {
      sendJson(res, 400, { ok: false, error: "Client ID and Client Secret are required." });
      return;
    }
    if (!clientId.includes(".apps.googleusercontent.com")) {
      sendJson(res, 400, {
        ok: false,
        error: "Client ID should look like ….apps.googleusercontent.com",
      });
      return;
    }
    const patch: Record<string, string> = {
      GOOGLE_OAUTH_CLIENT_ID: clientId,
      GOOGLE_OAUTH_CLIENT_SECRET: clientSecret,
      GOOGLE_OAUTH_REDIRECT_URI: OAUTH_REDIRECT,
    };
    if (typeof body.supabaseUrl === "string" && body.supabaseUrl.trim()) {
      patch.SUPABASE_URL = body.supabaseUrl.trim();
      patch.GOOGLE_ACCOUNTS_STORE = "supabase";
    }
    if (typeof body.supabaseServiceRoleKey === "string" && body.supabaseServiceRoleKey.trim()) {
      patch.SUPABASE_SERVICE_ROLE_KEY = body.supabaseServiceRoleKey.trim();
    }
    if (typeof body.tokenEncryptionKey === "string" && body.tokenEncryptionKey.trim()) {
      patch.GOOGLE_TOKEN_ENCRYPTION_KEY = body.tokenEncryptionKey.trim();
    } else if (patch.SUPABASE_URL && !parseEnvFile(envPath).GOOGLE_TOKEN_ENCRYPTION_KEY) {
      patch.GOOGLE_TOKEN_ENCRYPTION_KEY = randomBytes(32).toString("hex");
    }
    writeEnvFile(patch);
    sendJson(res, 200, { ok: true, redirectUri: OAUTH_REDIRECT, envPath });
    return;
  }

  if (req.method === "POST" && path === "/api/save-supabase") {
    const body = await readJson(req);
    const existing = parseEnvFile(envPath);
    if (!existing.GOOGLE_OAUTH_CLIENT_ID || !existing.GOOGLE_OAUTH_CLIENT_SECRET) {
      sendJson(res, 400, {
        ok: false,
        error: "Save your Google Client ID and Secret in step 3 first.",
      });
      return;
    }
    const supabaseUrl = String(body.supabaseUrl ?? "").trim();
    const supabaseServiceRoleKey = String(body.supabaseServiceRoleKey ?? "").trim();
    if (!supabaseUrl || !supabaseServiceRoleKey) {
      sendJson(res, 400, { ok: false, error: "Supabase URL and service_role key are required." });
      return;
    }
    if (!/^https:\/\/[a-z0-9-]+\.supabase\.co\/?$/i.test(supabaseUrl.replace(/\/$/, ""))) {
      // allow custom domains too — only require https
      if (!supabaseUrl.startsWith("https://")) {
        sendJson(res, 400, { ok: false, error: "Supabase URL must start with https://" });
        return;
      }
    }
    const patch: Record<string, string> = {
      GOOGLE_OAUTH_CLIENT_ID: existing.GOOGLE_OAUTH_CLIENT_ID,
      GOOGLE_OAUTH_CLIENT_SECRET: existing.GOOGLE_OAUTH_CLIENT_SECRET,
      SUPABASE_URL: supabaseUrl.replace(/\/$/, ""),
      SUPABASE_SERVICE_ROLE_KEY: supabaseServiceRoleKey,
      GOOGLE_ACCOUNTS_STORE: "supabase",
    };
    if (!existing.GOOGLE_TOKEN_ENCRYPTION_KEY) {
      patch.GOOGLE_TOKEN_ENCRYPTION_KEY = randomBytes(32).toString("hex");
    }
    writeEnvFile(patch);
    sendJson(res, 200, { ok: true, envPath });
    return;
  }

  if (req.method === "POST" && path === "/api/open-url") {
    const body = await readJson(req);
    const target = String(body.url ?? "").trim();
    const allowedPrefixes = [
      "https://console.cloud.google.com/",
      "https://supabase.com/",
      "https://app.supabase.com/",
      "https://cursor.com/",
      "https://www.cursor.com/",
      "https://docs.cursor.com/",
      "https://fly.io/",
      "https://www.fly.io/",
      "https://www.brandmatchgrowth.com/",
      "https://github.com/brandmathco/google-workspace-mcp",
      "https://accounts.google.com/",
    ];
    if (!allowedPrefixes.some((prefix) => target.startsWith(prefix))) {
      sendJson(res, 400, { ok: false, error: "That URL is not on the allow-list." });
      return;
    }
    openBrowser(target);
    sendJson(res, 200, { ok: true });
    return;
  }

  if (req.method === "GET" && path === "/api/migration-sql") {
    sendJson(res, 200, { sql: readMigrationSql(root) });
    return;
  }

  if (req.method === "GET" && path === "/api/fly/status") {
    sendJson(res, 200, getFlyStatus());
    return;
  }

  if (req.method === "POST" && path === "/api/fly/install") {
    const result = installFlyCli();
    sendJson(res, result.ok ? 200 : 500, { ...result, status: getFlyStatus() });
    return;
  }

  if (req.method === "POST" && path === "/api/fly/login") {
    const started = startFlyAuthLogin();
    if (!started.ok || !started.process) {
      sendJson(res, 400, { ok: false, error: started.error ?? "Could not start Fly login." });
      return;
    }
    const child = started.process;
    child.stdout?.on("data", () => undefined);
    child.stderr?.on("data", () => undefined);
    // Client polls /api/fly/status while the user finishes browser login.
    sendJson(res, 200, {
      ok: true,
      message: "A browser window should open for Fly.io sign-in. Come back here when finished.",
    });
    return;
  }

  if (req.method === "POST" && path === "/api/fly/deploy") {
    const body = await readJson(req);
    const env = parseEnvFile(envPath);
    const result = deployToFly(root, {
      appName: String(body.appName ?? "").trim(),
      region: String(body.region ?? "yyz").trim() || "yyz",
      googleClientId: String(body.googleClientId ?? env.GOOGLE_OAUTH_CLIENT_ID ?? "").trim(),
      googleClientSecret: String(
        body.googleClientSecret ?? env.GOOGLE_OAUTH_CLIENT_SECRET ?? "",
      ).trim(),
      supabaseUrl: String(body.supabaseUrl ?? env.SUPABASE_URL ?? "").trim(),
      supabaseServiceRoleKey: String(
        body.supabaseServiceRoleKey ?? env.SUPABASE_SERVICE_ROLE_KEY ?? "",
      ).trim(),
      mcpApiKey: typeof body.mcpApiKey === "string" ? body.mcpApiKey : undefined,
      authorizeHashKey:
        typeof body.authorizeHashKey === "string"
          ? body.authorizeHashKey
          : env.AUTHORIZE_HASH_KEY,
      tokenEncryptionKey:
        typeof body.tokenEncryptionKey === "string"
          ? body.tokenEncryptionKey
          : env.GOOGLE_TOKEN_ENCRYPTION_KEY,
    });
    if (result.ok && result.redirectUri) {
      // Keep local env in sync with remote Google redirect for future edits
      writeEnvFile({
        GOOGLE_OAUTH_CLIENT_ID: String(
          body.googleClientId ?? env.GOOGLE_OAUTH_CLIENT_ID ?? "",
        ).trim(),
        GOOGLE_OAUTH_CLIENT_SECRET: String(
          body.googleClientSecret ?? env.GOOGLE_OAUTH_CLIENT_SECRET ?? "",
        ).trim(),
        SUPABASE_URL: String(body.supabaseUrl ?? env.SUPABASE_URL ?? "").trim(),
        SUPABASE_SERVICE_ROLE_KEY: String(
          body.supabaseServiceRoleKey ?? env.SUPABASE_SERVICE_ROLE_KEY ?? "",
        ).trim(),
        GOOGLE_ACCOUNTS_STORE: "supabase",
      });
    }
    sendJson(res, result.ok ? 200 : 500, result);
    return;
  }

  if (req.method === "POST" && path === "/api/authorize") {
    const body = await readJson(req);
    const label = typeof body.label === "string" ? body.label : undefined;
    const result = await startAuthorize(label);
    sendJson(res, result.ok ? 200 : 400, result);
    return;
  }

  if (req.method === "POST" && path === "/api/authorize/cancel") {
    oauthBusy = false;
    oauthServer?.close();
    oauthServer = null;
    sendJson(res, 200, { ok: true });
    return;
  }

  if (req.method === "GET" && path === "/api/accounts") {
    sendJson(res, 200, { accounts: await listAccountsSafe(), oauthBusy });
    return;
  }

  if (req.method === "GET" && path === "/api/cursor-config") {
    sendJson(res, 200, {
      snippet: cursorMcpSnippet(root, envPath),
      paths: cursorConfigPaths(),
      distPath: mcpDistIndex(root),
      nodeCommand: resolveNodeCommand(root),
      envPath,
    });
    return;
  }

  if (req.method === "POST" && path === "/api/write-cursor-config") {
    if (!distBuilt(root)) {
      sendJson(res, 400, {
        ok: false,
        error: packaged
          ? "Installer is missing the MCP server files. Re-download the app from GitHub Releases."
          : "Build the project first (Install step).",
      });
      return;
    }
    if (!existsSync(envPath)) {
      sendJson(res, 400, {
        ok: false,
        error: "Save your Google keys first so Cursor can load them.",
      });
      return;
    }

    const target = cursorConfigPaths()[0];
    mkdirSync(dirname(target), { recursive: true });

    let existing: { mcpServers?: Record<string, unknown> } = {};
    if (existsSync(target)) {
      try {
        existing = JSON.parse(readFileSync(target, "utf8")) as typeof existing;
      } catch {
        const backup = `${target}.bak-${Date.now()}`;
        copyFileSync(target, backup);
        existing = {};
      }
    }

    const next = {
      ...existing,
      mcpServers: {
        ...(existing.mcpServers ?? {}),
        "google-workspace": {
          command: resolveNodeCommand(root),
          args: [mcpDistIndex(root)],
          env: {
            GOOGLE_MCP_ENV_FILE: envPath,
            GOOGLE_MCP_APP_ROOT: root,
          },
        },
      },
    };

    writeFileSync(target, `${JSON.stringify(next, null, 2)}\n`, "utf8");
    sendJson(res, 200, { ok: true, path: target });
    return;
  }

  sendJson(res, 404, { error: "Not found" });
}

function isDirectRun(): boolean {
  const entry = process.argv[1];
  if (!entry) return false;
  try {
    return import.meta.url === pathToFileURL(entry).href;
  } catch {
    return false;
  }
}

if (isDirectRun()) {
  const openBrowser =
    process.env.SETUP_WIZARD_NO_BROWSER !== "1" &&
    process.env.SETUP_WIZARD_NO_BROWSER !== "true";
  startWizardServer({ openBrowser }).catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });

  process.on("SIGINT", () => {
    oauthServer?.close();
    process.exit(0);
  });
}
